

import "./globals.css";
import Provider from "./providers";



export const metadata = {
  title: "TMDB API",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body className="bg-black text-white">
       <Provider>
        {children}
        </Provider>
      </body>
     
    </html>
  );
}
